title: Dominik Speckbacher — Research-oriented IT
description: Linux · Netzwerke · Automatisierung · DevSecOps · Bioinformatik/HPC
theme: minima

author:
  name: Dominik Speckbacher
  email: dominik.speckbacher@gfn.education

url: https://specklab.github.io
social_links:
  - { platform: linkedin,  user_url: "https://www.linkedin.com/in/dominik-speckbacher" }
  - { platform: github,    user_url: "https://github.com/specklab" }

# Seiten oben im Menü
header_pages:
  - projects.md
  - about.md
  - contact.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
